### ISSUE TITLE
Install instructions?

### ISSUE THREAD

**Issue by 2braincells2go** [geoffreybans/presentation-codeigniter#1]
Hi. Saw your post on strut...

Any install instructions?

I uploaded and get blank screen. Then set baseurl in /system/core/Config.php and still get blank page. Seems to be looking at localhost as see server IP in error console.

Thanks!

**Comment by geoffreybans** [comment]
Say your base url is http://localhost/presentation-codeigniter i.e. including the installation directory. Take that and paste it in this file here presentation-codeigniter/application/config/config.php line 26. 

It should now be $config['base_url'] = 'http://localhost/presentation-codeigniter'; and you should be good to do.

**Comment by 2braincells2go** [comment]
Now works fine.

Great job Geoffrey. Had thought of attempting something like this with Strut but seemed impossible. Now I see that was not true:)

If there was some simple way to export the finished presentation, would be perfect.

Thanks for sharing the knowledge.

Woody

**Comment by 2braincells2go** [comment]
Cannot see where mySQL is needed?

> This application based on CodeIgniter and MySQL creates powerpoint like presentations using html5 and CSS.

**Comment by geoffreybans** [comment]
My ultimate goal is to make it possible to save presentations in the database so that they can persist across different devices and browsers.
I haven't yet implemented the MySQL database part.
Still thinking of a better framework for the back end (Thinking of laravel or Rails) before I can decide on the database. A more popular framework would be better.
Meanwhile I will remove the statement that mentions 'MySQL' ..

**Comment by 2braincells2go** [comment]
Totally cool Geoffrey. Great job:)

Since my main use will be at school and not being able to use mySQL prefer the version you have now. Very simple to run from a local server with current setup. Was just wondering....

Only thing that would make your version rock the planet; is ability to save the presentation in HTML format. Users can of course use the browser "save as" but for younger users a button to accomplish would be excellent.

Thanks again.
